name = "puppergram"
compatibility_date = "2026-08-16"
pages_build_output_dir = "dist"

# Create with:  wrangler kv namespace create QUOTA
# then paste the id below and in the Cloudflare Pages dashboard binding.
[[kv_namespaces]]
binding = "QUOTA"
id = "8da178815ca846ee8807ee2fa0c018b9"
